alias: Miflora Boble notofication
trigger:
  platform: numeric_state
  entity_id: sensor.boble_moisture
  below: 16
action:
  service: notify.notify
  data:
    message: "Boble needs water"
    title: "Boble"
